version: '2.1'
services:
  server:
    image: node:8.11-slim
    container_name: serveur
    hostname: serveur
    ports:
      - '5432:5432'
  client:
    image: node:8.11-slim
    container_name: client
    hostname: client
    ports:
      - '1080:80'

  dev_db:
    image: mongo
    container_name: db
    hostname: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: {databaseUrl}