name: Deploy Prod Apps

on:
  push:
    branches:
      - githubAction
      - main

jobs:
  deploy:
    name: Deploy apps to prod
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install npm dependencies
        run: cd ui && npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: Rxinui/ssh-deploy-repo-action@v1
        with:
          ssh-user: ubuntu
          ssh-password: CTzCKyR0tbo27tsaYhjx
          ssh-domain: 54.88.215.35
          git-clone-by: ssh
          target-branch: develop
          target-directory: /ui/test
